genome_size: 13m
fastq_directory:
  class: Directory
  path: /storage/gitProjects/Workflows/Assembly/data/inputs
threads: 36
seq_technology: nanopore
min_coverage: 8
lineage: ascomycota
kingdom: Bacteria
prokaryotic: false
eukaryotic: true
prot_seq:
  class: File
  path:  /storage/gitProjects/Workflows/Assembly/data/prot_seq/uniprotkb_ascomycota_2024_11_06.fasta 