genome_size: 5.7m
fastq_directory:
  class: Directory
  path: /storage/gitProjects/Workflows/Assembly/data/klebsiella_pneumoniae
threads: 36
seq_technology: nanopore
min_coverage: 8
lineage: enterobacterales
kingdom: Bacteria
domain: prokaryotic
prot_seq:
  class: File
  path:  /storage/gitProjects/Workflows/Assembly/data/prot_seq/uniprotkb_ascomycota_2024_11_06.fasta 
taxon: 570
db_bakta:
  class: Directory
  path: /storage/gitProjects/Workflows/Assembly/data/bakta/db